### ISSUE TITLE
backend: Implement Contacts for User

### ISSUE THREAD

**Issue by samsara-lab** [lagital/Langeo#13]
Контактами пользователя я называю его ники/Id в соцсетях. Таким образом, контакт как сущность имеет два атрибута - id и тип. Пользователь может иметь несколько контактов.

Для начала предлагаю использовать две соц. сети - vk и Facebook. Соответственно и два типа контактов в виду enum. В приложении клик по контакту, воплощенному в виде элемента интерфейса, будет открывать соответствующее приложение с профилем пользователя.

**Comment by alkedr** [comment]
Можно сделать просто поля в User'е, без enum'ов.

**Comment by samsara-lab** [comment]
Их сложнее поддерживать. На основе enum (или хотя бы просто array с идентификаторами сетей) проще генерировать вьюхи со списками. Что если я решу добавить соц. сеть в поддерживаемые? Тогда мне придется обрабатывать новое поле. С enum/array я могу сделать общий метод, выполняющий разные операции в зависимости от входного значения.

**Comment by alkedr** [comment]
Их было бы существенно сложнее поддерживать если бы вариант с enum'ом позволял тебе добавить новую соцсеть просто добавив новый элемент в enum. Но ты никогда не сможешь добавить новую соцсеть просто добавив новый элемент в enum. Тебе всё нужно будет внести кучу изменений в приложение: добавить иконку в ресурсы, добавить кнопку куда-то, написать обработчик нажатия кнопки и т. д. Необходимость читать дополнительное поле – меньшая из проблем :).

**Comment by samsara-lab** [comment]
Я писал длинный коммент, но интернет лаганул и все убил. Короче, окей, пусть будут поля.

contactVk
contactFacebook
