### ISSUE TITLE
backend: Разделить id и email пользователя

### ISSUE THREAD

**Issue by alkedr** [lagital/Langeo#16]
Из-за старого бага Google App Engine или Google Endpoints я не могу получить настоящий гугловый id пользователя, только email. Использовать email везде в качестве id пользователя нехорошо, потому что всем будут видны email'ы все пользователей. Надо сделать искусственный id и использовать его везде где можно.

**Comment by samsara-lab** [comment]
Саша, но я же от тебя получаю вполне "здоровый" ID. И уже давно им оперирую. Или он фейковый?

**Comment by alkedr** [comment]
Да, я использовал сгенерированный id до тех пор, пока не наткнулся на вышеупомянутую багу.
Потом я хотел перейти на email'ы и даже что-то начал для этого делать.
Потом до меня дошло, что за такое надо стучать по голове кирпичом, и я создал эту таску.

**Comment by samsara-lab** [comment]
Саша, окей, держи в курсе :) А то айдишка уже сторится локально на телефон (в случае недоступности сервера юзеру в некоторых моментах на это становится пофиг).
