### ISSUE TITLE
Add UpdateCoordinates to LangeoAPI

### ISSUE THREAD

**Issue by samsara-lab** [lagital/Langeo#6]
I suggest to separate UpdateUser and UpdateCoordinates functionality with different calls to avoid overloading (devices will inform the server about their coordinates every N seconds).

**Comment by alkedr** [comment]
Начнём об этом думать когда пользователи начнут пользоваться, и мы начнём получать статистику о том, какие методы API самые тяжёлые и нуждаются в оптимизации.
Сейчас предлагаю сделать самый простой вариант.

**Comment by samsara-lab** [comment]
ОК, использую PutUser.
