### ISSUE TITLE
backend: Add GetMeetings call to LangeoAPI

### ISSUE THREAD

**Issue by samsara-lab** [lagital/Langeo#7]
FindNeighbors (or something like that) returns all users at the same town (with their coordinates).

**Comment by alkedr** [comment]
Нам нужно добавить поле "город"?
У тебя есть возможность на своей стороне получить город пользователя?

**Comment by samsara-lab** [comment]
Да, вариант с полем "город" - это ОК. Необходимо только на стороне бэкенда отличать пользователей онлайн от пользователей оффлайн - чтобы не возвращать весь ворох людей на запрос.

Завел таску на стороне приложения для определения города:
https://github.com/lagital/Langeo/issues/10

Нужно добавить поле Город в User на бэкенде.

**Comment by alkedr** [comment]
Ага, то есть ещё добавить флаг "онлайн"?

**Comment by alkedr** [comment]
Добавлю String cityId, потом разберёмся точно ли это String.

**Comment by samsara-lab** [comment]
Насчет "онлайн" - возможно, что это поле (выглядит логичным), но как с ним взаимодействовать мне не совсем ясно. В принципе, я могу на старте приложения слать оповещение о том, что пользователь онлайн, а на закрытии - что offline. Таким образом, если приложение "спит", то он продолжает получать нотификации о добавлении в чат, трекаться на карте и т.д.

**Comment by alkedr** [comment]
Ну, кажется, что у приложения больше информации о том, активен ли пользователь.
Но можно сделать и "время последнего запроса", это ненамного сложнее.

**Comment by samsara-lab** [comment]
С другой стороны, я "онлайн" для других пользователей только в том случае, если нажата кнопка динамической геолокации меня и окружающих. Когда она нажата, запросы на обновление моего положения идут каждые несколько секунд. Таким образом, если кнопку отжали, большой промежуток со времени последнего запроса действительно говорит о том, что юзер отключился. Так что время последнего запроса меня устраивает. Можно поставить искусственное ограничение, например, 3 минуты.

Кстати, когда геолокация активна, я не только должен получать других пользователей, но и обновлять для них себя. Предлагаю это сделать в один запрос, т.е. подавать пользователя или его id как один из входных параметров.

**Comment by alkedr** [comment]
А нам точно нужно отслеживать положение пользователей в реальном времени?
Может лучше будет позволить пользователю указать в каких местах он хочет встречаться с другими пользователями?

Это лучше подходит для случаев типа "пользователь сидит на работе и ищет с кем встретиться на выходных рядом со своим домом". Или "пользователь регулярно бывает рядом со своим домом и работой, и ему одинаково удобны оба места".

**Comment by samsara-lab** [comment]
Саша, да - это отличная идея! Предлагаю ввести на карту маркеры типа "встреча", у которых помимо, собственно координат будет список участников и время (от ... до ...). Тогда люди будут добавляться к встрече как в чат и приходить к положенному времени. Решение о принятии/непринятии пользователя к встрече принимает создатель встречи.

Надо только понять, оставлять ли геолокацию в реальном времени тогда ... Ее отсутствие значительно упростило бы жизнь и - что очень важно - энергопотребление.

**Comment by alkedr** [comment]
Ещё один аргумент против геолокации – далеко не все пользователи будут согласны сливать свои точные координаты какому-то неизвестному приложению и всем его пользователям.
Я думаю, что геолокацию надо как минимум отложить.

Получается нам нужны следующие запросы:
- создать встречу
- изменить встречу (доступен только создателю)
- предложить изменить встречу (доступен всем остальным пользователям)
- найти встречи по каким-то параметрам (что лучше, город или координаты?)

**Comment by samsara-lab** [comment]
Предлагаю так:

Класс "встреча":
- Создать встречу (координаты, имя, владелец, время from, время to, город)
- Обновить встречу - (параметры те же) - доступна только создателю.
- Присоединиться к встрече (встреча, юзер) - доступна тем, кто еще не вступил.
- Покинуть встречу (встреча, юзер)

Искать встречи предлагаю очень просто - они показываются на карте, причем все те, что в одном с тобой городе.
Предложить изменить - лишнее, мне кажется. Есть ведь чат.

**Comment by samsara-lab** [comment]
можно еще фильтр по дате/времени позволить задать для поиска встреч, но боюсь он на первых парах не нужен будет :)

**Comment by alkedr** [comment]
> Присоединиться к встрече (встреча, юзер) - доступна тем, кто еще не вступил.
> Предложить изменить - лишнее, мне кажется. Есть ведь чат.

А, то есть изменять встречи может только создатель, остальные юзеры будут просить его изменить. Окей. Да, так лучше.

> Искать встречи предлагаю очень просто - они показываются на карте, причем все те, что в одном с тобой городе.

То есть бэкенд должен уметь фильтровать по городу?
Или даже по городу первое время не будем делать? Просто отдавать все будущие встречи?

**Comment by samsara-lab** [comment]
Я бы уже начал фильтровать по городу. В общем-то, мы собирались это внедрять для юзеров - пусть будет вместо этого для встреч :)

Кстати вопрос, если мы вообще убираем юзеров с карты, то как быть с учителями ... Дать им возможность размещать статичные метки? Или всё же отображаться на карте - непонятно =\ можно, кончено, вообще на них забить и оставить только языковые школы (они как раз статичны). Но хотелось бы как-то оставить копеечку от физ. лиц :) Да и так интереснее.

**Comment by alkedr** [comment]
Можно как-нибудь выделять встречи, в которых участвует учитель.

**Comment by samsara-lab** [comment]
Т.е. я, как учитель, могу создавать "элитные" встречи?) в принципе почему бы и нет

**Comment by alkedr** [comment]
Скорее "делать встречу элитной своим присутствием".
Не важно кто создал, важно что там учитель есть.

**Comment by samsara-lab** [comment]
Тогда мы вынуждаем учителя активно участвовать во встречах - это может быть навящевым. Я, к примеру, могу предпочесть встречу без учителя, т.к. он по-любому впаривает всем свои визитки.

**Comment by alkedr** [comment]
Ну тогда ищи на карте встречи без учителя.
Или без твоего нелюбимого учителя.
Я не предлагаю сделать наличие учителя обязательным условием для встречи, я предлагаю для встреч с учителем сделать другую иконку на карте.
